For 456
OPEN-ENT-NG/form pull request #110
Opened 2022-09-30 12:23 UTC by c4role

## Describe your changes
Add new question type : cusor 
First part : edition view

## Checklist tests
You can create a new form or use an old one, and then you add a new cursor question ; you should be able to determine a minium value, a maximum one and a step ; you also can add optionnal label for those two value.
Value are required, and by default they respectivly are 1, 10 and 1.

## Issue ticket number and link
[FOR-456] https://jira.support-ent.fr/browse/FOR-456

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-30 13:10 UTC, JinDouang requested changes

2022-09-30 13:10 UTC, JinDouang commented on formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss
> +    -moz-appearance: textfield;
Il y a une raison de rajouter l'attribut moz pour Gecko (firefox) spécifiquement ?

2022-09-30 13:10 UTC, JinDouang commented on formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss
> +  input::-webkit-inner-spin-button {
Il y a une contrainte sur les autres nav (safari/firefox) pour être amené à utiliser webkit ?

2022-09-30 13:10 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
> +export const questionTypeCursor: Directive = ng.directive('questionTypeCursor', () => {
Il n'y avait pas moyen d'adapter la directive en mode classe ? Comme tu avais fait sur minetest 😁

2022-09-30 13:10 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +                .add(question.getInteger(CURSOR_STEP, null))
A confirmer (pas sur du comportement côté sql) mais si jamais tu n'as pas ces attributs, tu mets null par défaut mais du coup quand le sql côté java va lire cette value tu risques pas une NPE ?

2022-09-30 13:13 UTC, c4role commented on formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss
> +    -moz-appearance: textfield;
J'ai vu que pour firefox il fallait le spécifié de cette manière ?

2022-09-30 13:14 UTC, c4role commented on formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss
> +  input::-webkit-inner-spin-button {
Apparemment ça ne fonctionne pas de la même manière sur les différents navigateur pour toucher cet attribut

2022-09-30 13:15 UTC, c4role commented on formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
> +export const questionTypeCursor: Directive = ng.directive('questionTypeCursor', () => {
Sur formulaire tous les types de question sont centralisés donc je n'ai pas voulu "casser" la manière dont les autres ont été géré lors de l'ajout de ce nouveau type

2022-10-04 08:52 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +                .add(question.getInteger(CURSOR_STEP, null))
Je n'ai pas d'autre choix que de mettre null ici il me semble ; Il faut gérer le fait que dans un autre type de question, il n'y a pas ces champs qui sont donc pas défaut à null. Evo à venir : gérer ces fameux types dans une autre table qui contiendra les champs spécifiques.

2022-10-18 09:25 UTC, merged