feat(export/import) : [FOR-385] allow to export/import formulaire
OPEN-ENT-NG/form pull request #117
Opened 2022-10-17 14:51 UTC by qperie

## Describe your changes
Extension of #114.
Now we can select forms from Formulaire module, export them on the computer into a ZIP file and reimport them in Formulaire.
To do that we use the system of import/export previously implemented for the Archive module by calling Archive API endpoints.

## Checklist tests

## Issue ticket number and link
FOR-385 : https://jira.support-ent.fr/browse/FOR-385

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-17 14:58 UTC, qpic-cgi commented on common/src/main/java/fr/openent/form/helpers/MessageResponseHelper.java
>      public static Handler<AsyncResult<Message<JsonObject>>> messageJsonArrayHandler(Handler<Either<String, JsonArray>> handler) {
https://github.com/CGI-OPEN-ENT-NG/minibadge/blob/dev/src/main/java/fr/cgi/minibadge/helper/PromiseHelper.java#L40

P'tit tip, c'est purement informatif !

2022-10-17 15:05 UTC, qpic-cgi requested changes

2022-10-17 15:05 UTC, qpic-cgi commented on formulaire/src/main/resources/public/ts/controllers/forms-list.ts
> +            vm.display.lightbox.export = false;
vm.closeExportForms()

en vrai tu peux t'en servir non ? 😋

2022-10-17 15:11 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/forms-list.ts
> +            vm.display.lightbox.export = false;
Exact, bien vu ! 😄

2022-10-17 15:58 UTC, BastienBenard commented on common/src/main/resources/ts/services/FormService.ts
> +            return res.data.exportId;
Si c'est un string tu peux typer ta promise en String (Promise<string> au lieu de Promise<any>)

2022-10-17 15:58 UTC, BastienBenard commented on common/src/main/resources/ts/services/FormService.ts
> +            let verifyInfos = await http.get(`/archive/export/verify/${exportId}`);
Est ce que tu peux crée un model pour le retour d'api ? Si oui pence a changer le Promise\<any\>

2022-10-17 15:58 UTC, BastienBenard commented on common/src/main/resources/ts/services/FormService.ts
> +                return await http.post(`/archive/import/${importId}/launch`, { "apps": analyze.data.apps });
Est ce que tu peux crée un model pour le retour d'api ? Si oui pence a changer le Promise\<any\>

2022-10-17 15:58 UTC, BastienBenard commented on common/src/main/resources/ts/services/FormService.ts
> +            let source = CancelToken.source();
Est ce que c'est typable ?

2022-10-17 15:58 UTC, BastienBenard commented on common/src/main/resources/ts/services/ResponseService.ts
> +                return await http.post(`/formulaire/responses/export/${formId}/pdf`, images, {responseType: "arraybuffer"});
Est ce que tu peux crée un model pour le retour d'api ? Si oui pence a changer le Promise\<any\>

2022-10-17 15:58 UTC, BastienBenard commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +        RequestUtils.bodyToJsonArray(request, formIds -> {
Est ce que tu peux faire un jsonschema pour la validation du body ?

2022-10-17 15:58 UTC, BastienBenard commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +                            .put("resourcesIds", new JsonArray().addAll(formIds));
Magic String

2022-10-17 15:58 UTC, BastienBenard commented on formulaire/src/main/resources/public/ts/controllers/forms-list.ts
> +    vm.importForms = async () : Promise<void> => {
Pourquoi est ce que cette fonction est async ?

2022-10-17 15:58 UTC, BastienBenard commented on formulaire/src/main/resources/public/ts/controllers/forms-list.ts
> +    vm.exportForms = async () : Promise<void> => {
Pourquoi est ce que cette fonction est async ?

2022-10-18 07:42 UTC, qpic-cgi approved these changes

2022-10-18 07:44 UTC, JinDouang requested changes

2022-10-18 07:47 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +        RequestUtils.bodyToJsonArray(request, formIds -> {
Pas sur un JsonArray, mais je dois en faire pour d'autres endroits et réfléchir à est-ce que j'encapsule mon array dans un json classique pour utiliser un jsonschema après yes, c'est prévu dans un coin de ma tête 👍

2022-10-18 07:48 UTC, JinDouang requested changes

2022-10-18 07:48 UTC, JinDouang commented on common/src/main/resources/ts/services/FormService.ts
> +            return verifyInfos;
Au final tu n'as pas besoin de le return si tu fais window.location.href ?

Tu pourrais typer en Promise<void> je pense

2022-10-18 07:48 UTC, JinDouang commented on common/src/main/resources/ts/services/FormService.ts
> +            let source = CancelToken.source();
```suggestion
 const CancelToken: CancelTokenStatic = Axios.CancelToken;
 let source: CancelTokenSource = CancelToken.source();
```

2022-10-18 07:55 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/forms-list.ts
> +        window.setTimeout(async function () { await vm.$onInit(); }, 100);
Huum, intéressant ! Du coup j'vais plutôt m'en faire une petite issue et changer ça de façon globale je pense parce que j'ai le même principe dans d'autres controllers 👍

2022-10-18 09:44 UTC, JinDouang approved these changes

2022-10-18 09:53 UTC, merged