refacto(response) : [FOR-454] refacto response system in formulaire-public (without MATRIX)
OPEN-ENT-NG/form pull request #121
Opened 2022-10-21 13:27 UTC by qperie

## Describe your changes
First part of the refactoring of the response system.
It only impacts response system in formulaire-public and doesn't include MATRIX type questions.

## Checklist tests

## Issue ticket number and link
FOR-454 : https://jira.support-ent.fr/browse/FOR-454

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-21 16:16 UTC, qpic-cgi requested changes

2022-10-24 07:52 UTC, qperie commented on common/src/main/resources/ts/utils/public.ts
> +            let key: any = formElementMap[0];
Humm c'est du pur json qui est recup justement à ce moment là c'est pas typé. C'est pour ça que  lignes plus tard grâce à ses infos je recup mon objet typé correspondant.

2022-10-24 07:53 UTC, qperie commented on formulaire-public/src/main/resources/public/template/containers/respond-question.html
> +<!--            </public-matrix>-->
Comme expliqué dans la description c'est une première version sans la gestion des matrices. Je les ai comment pour que ça fonctionne bien, prochaine PR justement ce sera la gestion des matrices :)

2022-10-24 07:53 UTC, qperie commented on formulaire-public/src/main/resources/public/template/containers/respond-question.html
> +<!--                        </public-matrix>-->
Pareil que le commentaire précédent

2022-10-24 07:56 UTC, qpic-cgi approved these changes

2022-10-24 14:27 UTC, merged