feat(question-type-cursor): #FOR-458 create result view with graph
OPEN-ENT-NG/form pull request #126
Opened 2022-10-28 15:25 UTC by c4role

## Describe your changes
Create result view with an apexchart type area & export PDF

## Checklist tests
Create a form (or use an old one), add question type cursor ; share it and create two or more answers then go to result view and check if your graph is coherent, and average is okay. You also can try to export it in PDF.

## Issue ticket number and link
[FOR-458] https://jira.support-ent.fr/browse/FOR-458

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-02 07:02 UTC, sjollois requested changes

2022-11-02 07:02 UTC, sjollois commented on common/src/main/resources/ts/utils/graph.ts
> +        for (let r of reponses) {
Code dupliqué, tu peux pas en faire une fonction appelé deux fois ?

2022-11-02 07:02 UTC, sjollois commented on common/src/main/resources/ts/utils/graph.ts
> +                        text: 'Modalité de réponses' + ' (' + cursorAverage + ')'
i18n ?

2022-11-02 13:15 UTC, SLedunois commented on common/src/main/resources/ts/utils/graph.ts
> +    static generateGraphForResult = (question: Question, chart: any, responses?: Responses) : void => {
Tu devrais passer une valeur par défaut pour le parametre responses. Dans ta fonction `generateCursorChart`, le meme parametre n'est pas optionel et tu risques de generer une erreur en ligne 101.

2022-11-02 13:40 UTC, JinDouang requested changes

2022-11-02 13:40 UTC, JinDouang commented on common/src/main/resources/ts/utils/graph.ts
> +                        text: 'Modalité de réponses' + ' (' + cursorAverage + ')'
cf commentaire au dessus avec lang.translate

2022-11-02 13:40 UTC, JinDouang commented on common/src/main/resources/ts/utils/graph.ts
> +        newOptions.series = [{ name: "Modalité de réponse", data: Array.from(map.values()) }];
Tu pourrais utiliser lang.translate('form.modality.response')
```suggestion
        newOptions.series = [{ name: lang.translate('form.modality.response'), data: Array.from(map.values()) }];
```

2022-11-15 10:24 UTC, sjollois approved these changes

2022-11-15 11:07 UTC, qperie requested changes

2022-11-15 11:07 UTC, qperie commented on common/src/main/resources/ts/utils/graph.ts
>              case Types.SINGLEANSWER:
Tu as déjà géré le SINGLEANSWER case ligne 19 normalement.
Si tu laisses comme ça et que tu appelles cette fonction avec le case SINGLEANSWER ça va appeler generateMultipleAnswerChartForPDF() ce qui n'est pas ce qu'on veut !

2022-11-15 11:07 UTC, qperie commented on common/src/main/resources/ts/utils/graph.ts
>              case Types.MULTIPLEANSWER:
Tu peux très bien le mettre avec les autres en haut, ça fera plus qu'un seul switch !
La seule particularité du MULTIPLEANSWER c'est juste qu'il est appelé que pour du pdf pour l'instant mais tu peux très bien le gérer comme les autres :)

2022-11-22 13:56 UTC, qperie approved these changes

2022-11-22 14:00 UTC, merged