feat(question-type-cursor): #FOR-498 sync question specific field's in eventBus
OPEN-ENT-NG/form pull request #181
Opened 2023-01-17 16:17 UTC by c4role

## Describe your changes
Sync specific field's in eventBus for 'formulaire-public' + refacto

## Checklist tests
Create a new public form with at least a question type cursor, share it and check if input type range is correct (specificly the blue part)

## Issue ticket number and link
[FOR-498](https://jira.support-ent.fr/browse/FOR-498)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-17 16:56 UTC, alicedraillard approved these changes

2023-01-17 17:07 UTC, qperie requested changes

2023-01-17 17:07 UTC, qperie commented on formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
> +        defaultQuestionService.listForFormAndSection(FORM_ID);
Les tests de promise sont pas exactement comme les tests de handler, voilà un exemple : https://github.com/OPEN-ENT-NG/form/pull/171/files#diff-a5cfb3e7320d43c298ca02ad201e5dc771d28ca88ae382cf18f54500a86b6c0c

2023-01-17 17:07 UTC, qperie commented on formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
> +        defaultQuestionSpecificFieldService.listByIds(questionIds);
cf au-dessus

2023-01-18 08:32 UTC, qpic-cgi approved these changes

2023-01-18 13:23 UTC, qperie approved these changes
Juste le logger à changer mais impec' pour le reste 👍

2023-01-18 13:23 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldService.java
> +    private static final Logger log = LoggerFactory.getLogger(QuestionController.class);
Attention à la class passée pour le logger

2023-01-19 08:21 UTC, merged