feat(questionChoice): [#FOR-531] add next element target for section
OPEN-ENT-NG/form pull request #246
Opened 2023-04-07 13:11 UTC by qperie

## Describe your changes
We now allow a section to target another form element to create a flow of response which not need conditional questions.
This includes :
- add **next_form_element_id** and **next_form_element_type** properties
- by default the the target is the next element
- it updates even when elements are drag and drops
- when answering it should follow the flow defined with targetting system

## Checklist tests
Creator side :
- Create a section
- Target another element (before should be forbidden, after should work)
- A conditional question in the section should block and hide the possiblity for the parent section to target
- The responses behaviour can be tested with the preview

Response side :
- The questions/sections should follow as expected as defined thanks to the targetting system

## Issue ticket number and link
FOR-531 : https://jira.support-ent.fr/browse/FOR-531

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-12 08:37 UTC, JinDouang requested changes

2023-04-12 08:37 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultSectionService.java
> +        else if (section.getNextFormElementId() == null ^ section.getNextFormElementType() == null) {
Qu'est-ce que c'est `^`

2023-04-12 17:21 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultSectionService.java
> +        else if (section.getNextFormElementId() == null ^ section.getNextFormElementType() == null) {
^ = XOR -> renvoie true si les deux valeurs sont différentes, renvoie faux si les deux ont des valeurs

2023-04-17 09:06 UTC, alicedraillard approved these changes

2023-04-18 06:24 UTC, JinDouang approved these changes

2023-04-18 08:44 UTC, merged