FOR-280 Export PDF
OPEN-ENT-NG/form pull request #251
Opened 2023-05-02 13:17 UTC by c4role

## Describe your changes
Can export question's form to PDF

## Checklist tests
You can create a form, add sections and/or questions, and then export it. Simple right ? Spoiler alert, no it's not.

## Issue ticket number and link
[FOR-280](https://jira.support-ent.fr/browse/FOR-280)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-02 13:53 UTC, c4role commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <!-- Réponse unique, radio btn -->
Idem pour ces sales commentaires en français

2023-05-02 14:28 UTC, Rseuret approved these changes

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                    <div style="border: 1px solid black; padding: 10px;">
[Optimisation]tu peux créer une classe plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                    <div class="radio-buttons-container" style="display: flex; flex-direction: column">
[Optimisation]tu peux créer une classe plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                    <div class="checkbox-container" style="display: flex; flex-direction: column">
[Optimisation]tu peux créer une classe plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <div style="border-bottom: 1px solid black; margin-top: 5px; width: 30px;"></div>
[Optimisation]tu peux créer une classe plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <th style="border-bottom: 1px solid black; padding: 5px;">{{value}}</th>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                    <table class="matrix-table" style="border-collapse: collapse;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <th style="border-right: 1px solid black; padding: 5px;">{{title}}</th>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <td style="border-right: 1px solid black; padding: 5px; text-align: center;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <div style="border-bottom: 1px solid black; flex-grow: 1;"></div>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <div style="display: flex; flex-direction: column; align-items: flex-start; margin-left: 10px;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                {{title}}{{#mandatory}}<span style="color:red;margin-left:10px">*</span>{{/mandatory}}
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <div class="freetext-border" style="border: 1px solid black; padding: 10px;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <div style="border-bottom: 1px solid black; margin-top: 5px; width: 30px;"></div>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                                <th style="border-bottom: 1px solid black; padding: 5px;">{{value}}</th>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <table class="matrix-table" style="border-collapse: collapse;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <div class="radio-buttons-container" style="display: flex; flex-direction: column">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                        <div class="checkbox-container" style="display: flex; flex-direction: column">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                                <th style="border-right: 1px solid black; padding: 5px;">{{title}}</th>
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                                <td style="border-right: 1px solid black; padding: 5px; text-align: center;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 14:28 UTC, Rseuret commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                            <div style="display: flex; flex-direction: column; align-items: flex-start; margin-left: 10px;">
[Optimisation]tu peux créer une classe css plutôt que de faire du style

2023-05-02 15:00 UTC, qperie requested changes

2023-05-02 15:38 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +    public void launch() {
Entièrement d'accord, c'est le sujet principal du ticket optimisation à la base

2023-05-02 15:42 UTC, alicedraillard approved these changes

2023-05-02 15:42 UTC, alicedraillard commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +    private void generatePDF(HttpServerRequest request, JsonObject templateProps, String templateName, Handler<Buffer> handler) {
est-ce qu'il y a moyen de mettre cette méthode dans un helper (PDFHelper par exemple) ? Ca allègerait le fichier

2023-05-02 15:42 UTC, alicedraillard commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                node = (String) vertx.sharedData().getLocalMap("server").get("node");
tu peux faire des field pour server, node, content, baseUrl etc

2023-05-02 15:46 UTC, qpic-cgi approved these changes

2023-05-02 19:55 UTC, c4role commented on common/src/main/resources/ts/services/FormService.ts
> +    async export(formIds: number[], type: string) : Promise<any> {
N'a pas l'air de fonctionner car de type AxiosResponse

2023-05-02 19:59 UTC, c4role commented on common/src/main/java/fr/openent/form/core/constants/Fields.java
> +    public static final String SECTION_TITLE = "title";
Non en effet finalement je ne m'en sers pas

2023-05-02 20:01 UTC, c4role commented on formulaire/src/main/resources/public/template/pdf/questions.xhtml
> +                                <input type="radio" name="{{../id}}_{{../../id}}_{{../../id}}_{{../id}}" value="{{id}}_{{id}}" />
Non c'est un oubli quand j'ai fait des tests au début de mes tableaux, je retire

2023-05-02 20:43 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                                        }
Alors en ternaire ici ça ne fonctionne pas, mais en effet je peux simplifier comme ceci : 
if (question.containsKey(CHILDREN)) {
                question.getJsonArray(CHILDREN).add(child);
  } else {
                question.put(CHILDREN, new JsonArray().add(child));
  }

2023-05-02 20:45 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +    private void generatePDF(HttpServerRequest request, JsonObject templateProps, String templateName, Handler<Buffer> handler) {
Oui c'est prévu dans le ticket d'opti, d'autant plus qu'un autre export utilise la même !

2023-05-02 20:56 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                JsonObject promiseInfos = new JsonObject();
Je me le note dans le ticket d'optimisation, merci !

2023-05-03 07:42 UTC, qpic-cgi commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +    @Post("/forms/export/:fileType")
Perso, j'aurais fait vraiment 2 endpoint différents :
- @Post("/forms/export/zip")
- @Post("/forms/export/pdf")
ça permet de distinguer les 2 traitement et de t'éviter ce switch case plus bas.

2023-05-03 07:44 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +    @Post("/forms/export/:fileType")
En fait on a déjà fait comme ça pour un autre export où on fait la même chose, donc j'ai "uniformisé" et repris la même logique

2023-05-03 08:25 UTC, qperie approved these changes

2023-05-03 08:25 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +    @Post("/forms/export/:fileType")
Ouais on en a discuté avec q3, coté réponses ça avait un peu plus de logique parce qu'on on changeait juste le format, ici un peu moins c'est vrai, ça pourrait être bien de le scinder effectivement

2023-05-03 11:37 UTC, merged

2023-05-03 11:58 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +    @Post("/forms/export/:fileType")
OK je me le note alors