feat(matrix-multipleanswer): #FOR-610 add select in creation view
OPEN-ENT-NG/form pull request #267
Opened 2023-05-16 10:22 UTC by c4role

## Describe your changes
Add select to choose single or multipleanswer for matrix

## Checklist tests

## Issue ticket number and link
[FOR-610](https://jira.support-ent.fr/browse/FOR-610)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-16 12:53 UTC, qperie requested changes

2023-05-16 12:53 UTC, qperie commented on formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.directive.ts
> +    types: typeof Types;
C'est pas des props de la directive, il faut les mettre plutôt dans le IViewModel
Et à l'inverse il manque matrixType et matrixTypes dans tes props

2023-05-16 12:53 UTC, qperie commented on formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.directive.ts
> +    types: typeof Types;
Il manque la déclaration de "type" ici

2023-05-16 12:53 UTC, qperie commented on formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.directive.ts
> +        this.types = Types;
Si tu reçois "types" via les props de ta directive tu devrais pas avoir besoin de l'initialiser ici

2023-05-16 12:53 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +        int questionType = question.getInteger(QUESTION_TYPE, 1);
Pourquoi faire sauter la vérification ?

2023-05-16 12:53 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +                int questionType = question.getInteger(QUESTION_TYPE, 1);
cf commentaire précédent

2023-05-17 06:27 UTC, JinDouang requested changes

2023-05-17 06:27 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.directive.ts
> +        this.I18n = I18nUtils;
attention au nommage de variable = i18n plutôt qu'I18n

2023-05-17 06:27 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.html
> +                        [[vm.I18n.translate('formulaire.matrix.type.' + vm.types[matrixType])]]
cf commentaire nommage variable

2023-05-17 06:29 UTC, JinDouang commented
Et pour info, sur ta branche, tu as un test qui fail

2023-05-17 15:56 UTC, qperie approved these changes

2023-05-17 15:56 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +                && question.getInteger(QUESTION_TYPE, 1) != QuestionTypes.MULTIPLEANSWER.getCode()
Au lieu de verif les deux, le !MATRIX_CHILD_QUESTIONS.contains(question.getInteger(QUESTION_TYPE, 1)) utilisé avant fonctionne très bien (en s'assurant que MATRIX_CHILD_QUESTIONS inclue bien les deux types de questions)
Et pareil plus bas

2023-05-17 16:01 UTC, qperie requested changes
J'ai missclick et mis approve juste avant, je remet request changes pour l'histoire du DefaultQuestionService quand même 👍

2023-05-22 06:37 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
> +                && question.getInteger(QUESTION_TYPE, 1) != QuestionTypes.MULTIPLEANSWER.getCode()
OK, justement il n'inclue pas les bons. Mais vu qu'on ne l'utilise qu'ici, je peux donc modifié le MATRIX_CHILD_QUESTIONS en ajoutant MULTIPLEANSWER et retirant SINGLEANSWER ?

2023-05-22 09:14 UTC, qperie approved these changes

2023-05-22 12:10 UTC, JinDouang approved these changes

2023-05-22 12:12 UTC, merged