fix(exportPDF): #FOR-628 handle display of next titles for conditional questions when exporting
OPEN-ENT-NG/form pull request #284
Opened 2023-06-12 09:09 UTC by Gregprod33

## Describe your changes
When exporting a form in pdf with conditional questions within a section, each question has now the title of the relative form element to which that question points.
Also the question choices are now in the right order on pdf.
## Checklist tests
Export a form with conditional questions whithin and without sections.
## Issue ticket number and link
[FOR-628](https://jira.support-ent.fr/browse/FOR-628)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-06-12 09:41 UTC, qpic-cgi requested changes

2023-06-12 09:41 UTC, qpic-cgi commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                                    for (int i = 0; i < questions.size(); i++) {
stream "questions" plutôt pour boucler dessus

2023-06-12 09:41 UTC, qpic-cgi commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                                for (int i = 0; i < sectionQuestions.size(); i++) {
stream "sectionQuestions" plutôt pour boucler dessus

2023-06-12 09:41 UTC, qpic-cgi commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            // Handle next title to conditional questions within sections
Si tu mets un commentaire au dessus d'un bloc de code pour expliquer ce qu'il fait, c'est que tu peux en faire une fonction

2023-06-12 09:41 UTC, qpic-cgi commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            // Update choices with right datas
Si tu mets un commentaire au dessus d'un bloc de code pour expliquer ce qu'il fait, c'est que tu peux en faire une fonction

2023-06-12 09:53 UTC, Gregprod33 commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                                    for (int i = 0; i < questions.size(); i++) {
Le code entier sera revu en stream lors de la refacto, c'est prévu, là il s'agit d'un patch

2023-06-12 09:54 UTC, Gregprod33 commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                                for (int i = 0; i < sectionQuestions.size(); i++) {
Le code entier sera revu en stream lors de la refacto, c'est prévu, là il s'agit d'un patch

2023-06-12 09:56 UTC, Gregprod33 commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            // Handle next title to conditional questions within sections
Refacto prévue dans le prochain sprint, les commentaires me servent à délimiter les étapes pour le moment

2023-06-12 09:56 UTC, Gregprod33 commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            // Update choices with right datas
Refacto prévue dans le prochain sprint, les commentaires me servent à délimiter les étapes pour le moment

2023-06-12 09:57 UTC, qpic-cgi approved these changes

2023-06-12 10:01 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +import com.mongodb.util.JSON;
Je pense que cet import est useless

2023-06-14 07:17 UTC, Gregprod33 commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +import com.mongodb.util.JSON;
yes remove

2023-06-14 07:18 UTC, merged