chore(css): #FOR-684 migrate css within module
OPEN-ENT-NG/form pull request #298
Opened 2023-06-26 10:56 UTC by Gregprod33

## Describe your changes
*Migrate css inside the module as mentioned in the documentation :
https://confluence.support-ent.fr/display/DN/Packager+du+CSS+dans+un+module*
## Checklist tests
*Make a css change like a red backround color and then buils css from the build.sh of the module and watch the changes in the browser.*
## Issue ticket number and link
[FOR-684](https://jira.support-ent.fr/browse/FOR-684)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-06-26 13:16 UTC, JinDouang requested changes

2023-06-26 13:16 UTC, JinDouang commented on .github/workflows/dev-check-repository.yml
>        - name: Run test
Il manque l'instruction pour tester le build scss

2023-06-26 13:16 UTC, JinDouang commented on build.sh
> +}
(optionnel) 

Tu devrais rajouter 2 tâches de buildGulp pour préciser formulaire et formulaire-public

2023-06-26 14:51 UTC, Gregprod33 commented on .github/workflows/dev-check-repository.yml
>        - name: Run test
J'ai ajouté les l'instruction

2023-06-26 14:52 UTC, Gregprod33 commented on build.sh
> +}
J'ai recréé 2 tâches, ça te parait ok ?

2023-06-27 06:09 UTC, simonchaval approved these changes

2023-06-27 14:42 UTC, qperie approved these changes

2023-06-29 14:07 UTC, merged