fix(progressBar): #FOR-690 change method of progress bar rendering when answering a form
OPEN-ENT-NG/form pull request #306
Opened 2023-07-03 08:37 UTC by Gregprod33

## Describe your changes
Now the progress bar takes the longest path each time the user is answering a question. As the form can have some conditional question leading to other parts of the form, the new method calculates the longest path regarding the conditional choices and the different possibilities of user's answers.
## Checklist tests
Open a form with a user whom the form has been shared.
Answer the questions and the progress bar must adapt to your choices.
If you want to check whether the path is correct, open the edit page of the form whith the user who has created it and count the max number of form elements we can answer. You can use the new tree for view to be more confortable.
## Issue ticket number and link
[FOR-590](https://jira.support-ent.fr/browse/FOR-590)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-03 09:29 UTC, qperie requested changes
Maintenant qu'on peut remettre des images, rajoutes un schéma qui explique un peu avec une arborescence comme on avait vu au début du ticket, ce sera parlant pour les lecteurs

2023-07-03 09:29 UTC, qperie commented on common/src/main/resources/ts/directives/progress-bar.ts
> +    longestPath: number;
Manque historicPosition ici

2023-07-03 09:29 UTC, qperie commented on common/src/main/resources/ts/directives/progress-bar.ts
> +            nbFormElements: '=',
nbFormElements ne semble plus utilisé

2023-07-03 09:29 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +        };
- t'es décalé en indentation par rapport aux autres fonctions
- on utilise plutôt let que const pour toutes les variables dans tes fonctions en général
- type bien tes variables (conditionalQuestions, choices, ...)

2023-07-03 09:29 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +    }
Mêmes remarques que pour ta fonction d'au dessus (let, typages, ...)

2023-07-03 11:32 UTC, qperie requested changes

2023-07-03 11:32 UTC, qperie commented on common/src/main/resources/ts/directives/progress-bar.ts
> +    nbFormElements: number,
nbFormElements n'est plus utilisé

2023-07-03 11:32 UTC, qperie commented on formulaire/src/main/resources/public/template/containers/respond-question.html
> +    <progress-bubble-bar form-element="vm.formElement" nb-form-elements="vm.nbFormElements" longest-path="vm.longestPath"
nb-form-elements n'est plus utilisé

2023-07-03 11:32 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +            let choices: any = conditionalQuestions && conditionalQuestions.length > 0 ? conditionalQuestions.flatMap(q => q.choices.all) : null;
```suggestion
            let choices: Question[] = (conditionalQuestions && conditionalQuestions.length > 0) ? conditionalQuestions.flatMap((q: Question) => q.choices.all) : null;
```

2023-07-03 11:32 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +            let tab: any[] = choices.map((choice: any) => {
```suggestion
            let tab: number[] = choices.map((choice: any) => {
```

2023-07-04 07:33 UTC, Gregprod33 commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +            let tab: any[] = choices.map((choice: any) => {
modifié

2023-07-04 07:33 UTC, Gregprod33 commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +            let choices: any = conditionalQuestions && conditionalQuestions.length > 0 ? conditionalQuestions.flatMap(q => q.choices.all) : null;
Modifié pour le type de "choices", par contre le typage de "q" me sort une erreur

2023-07-04 07:33 UTC, Gregprod33 commented on formulaire/src/main/resources/public/template/containers/respond-question.html
> +    <progress-bubble-bar form-element="vm.formElement" nb-form-elements="vm.nbFormElements" longest-path="vm.longestPath"
modifié

2023-07-04 07:33 UTC, Gregprod33 commented on common/src/main/resources/ts/directives/progress-bar.ts
> +    nbFormElements: number,
modifié

2023-07-04 08:01 UTC, qperie approved these changes

2023-07-04 09:12 UTC, merged