fix(exportPDF): #FOR-609 factorize whole exportQuestionPDF file
OPEN-ENT-NG/form pull request #319
Opened 2023-07-12 11:13 UTC by Gregprod33

## Describe your changes
The entire FormQuestionsExportPDF has been refactorized
## Checklist tests
Create a form with all kind of form elements and export it. Check if all elements are present in PDF and well displayed.
## Issue ticket number and link
[FOR-609](https://jira.support-ent.fr/browse/FOR-609)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-12 13:23 UTC, aymericdevriesere commented on common/src/main/java/fr/openent/form/core/constants/Fields.java
> +    public static final String RADIO_BTN = "is_radio_btn";
same

2023-07-12 13:23 UTC, aymericdevriesere commented on common/src/main/java/fr/openent/form/core/constants/Fields.java
> +    public static final String SHORT_ANSWER = "is_short_answer";
same

2023-07-12 13:23 UTC, aymericdevriesere commented on common/src/main/java/fr/openent/form/core/constants/Fields.java
> +    public static final String TYPE_FREETEXT = "is_type_freetext";
same

2023-07-12 13:23 UTC, aymericdevriesere commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +                                            String errMessage = "[Formulaire@exportForm] No form found for id " + formIds;
c'est une liste le "formIds" ? si tu ne cherche que pour un id, pourquoi ne pas le mettre direct ?

2023-07-12 15:15 UTC, qperie requested changes

2023-07-12 15:15 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                question.put(DATE_HOUR, true);
Penser à changer toutes les constantes ici quand tu les renommeras (cf commentaire d'Aymeric au début)

2023-07-12 15:15 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                        section.put("questions", question);
magic string

2023-07-17 07:30 UTC, JinDouang requested changes

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +        JsonArray form_elements = new JsonArray();
camelCase (convention java)

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                    notFound(request);
Risque usage de l'objet request Http : 

Si jamais on appelle la fonction launch par un autre service (On supposerait dans ce cas qu'on a trouvé un moyen d'implémenter notre objet `request` dans le service donc on sera confronté à un autre risque) 
On risque de répondre à l'API tout en continuant le process dans le code.

A eviter à tout prix de mettre `request` dans nos fonctions métiers

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                CompositeFuture.all(imageInfos).onComplete(evt -> {
Tu pourrais avoir un `onSuccess` et un `onFailure`, ça t'éviterait d'avoir à gérer ton event.failed

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            request.response()
finalement la fonction `launch` pourrait retourner un Buffer pour que ton controller applique la réponse du request du pdf

On pourrait déplacer cette logique

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                String errMessage = String.format("[Formulaire@FormQuestionsExportPDF::launch]  " +
Il faut gérer les erreurs afin que le controller qui appelle cette fonction puisse au moins répondre

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +    private void fillChoicesImages(List<Future>imageInfos, Map<String, String> localChoicesMap, JsonObject choicesInfos){
Typage de la liste de future (JsonObject il me semble d'après la lecture du code)

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +    private void fillChoices(JsonObject questionChoices, Map<Integer, JsonObject>mapSections, Map<Integer, JsonObject>mapQuestions, List<Future> imageInfos){
typage

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +        List<JsonObject> childrenList = matrixChildren.getList();
Unchecked type quand tu get `getList`

Le risque c'est que je peux t'envoyer un JsonArray contenu que des list de string

Tu peux "résoudre" ce problème en stream : 

```suggestion
         List<JsonObject> childrenList = matrixChildren.stream()
                .filter(JsonObject.class::isInstance)
                .map(JsonObject.class::cast)
                .collect(Collectors.toList());
```

Tu peux même rajouter ton sort dans ton stream à la suite : 

```
   List<JsonObject> childrenList = matrixChildren.stream()
                .filter(JsonObject.class::isInstance)
                .map(JsonObject.class::cast)
                .sorted(Comparator.nullsFirst(Comparator.comparingInt(a -> a.getInteger(MATRIX_POSITION))))
                .collect(Collectors.toList());
```

2023-07-17 07:30 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                    List<JsonObject> choicesList = choices.getList();
A résoudre en stream (cf commentaire au-dessus)

2023-07-20 06:37 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +        List<Future> imageInfos = new ArrayList<>();
Pour imageInfos, je ne peux pas le typer en JsonObject car je le réutilise dans mon compositeFuture.all() qui lui attend une List<Future>

2023-07-20 13:23 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +                            request.response()
Fait essentiellement dans un autre ticket à venir

2023-07-20 13:49 UTC, JinDouang requested changes

2023-07-20 13:49 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +        List<Future> imageInfos = new ArrayList<>();
Ah bien vu! Ca marche pas nativement
Dans ce cas tu peux utiliser FutureHelper.all (cf code https://github.com/OPEN-ENT-NG/form/blob/FOR-609/common/src/main/java/fr/openent/form/helpers/FutureHelper.java#L118)

C'est l'équivalent du CompositeFuture.all() sauf qu'avec le FutureHelper c'est en mode type!

2023-07-20 14:28 UTC, c4role commented on formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
> +        List<Future> imageInfos = new ArrayList<>();
Tout à fait, merci à toi

2023-07-20 14:35 UTC, qperie approved these changes

2023-07-20 15:33 UTC, JinDouang approved these changes

2023-07-20 15:38 UTC, merged