feat(files): [#FOR-592] send notification when infected file is upload
OPEN-ENT-NG/form pull request #321
Opened 2023-07-13 16:14 UTC by qperie

## Describe your changes
Catch infected file alert and send a notification to all the contibutors of the form when it happens.

## Checklist tests

## Issue ticket number and link
FOR-592 : https://jira.support-ent.fr/browse/FOR-592

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-13 16:35 UTC, BastienBenard reviewed
Il manque juste des tests sur les services

2023-07-17 07:36 UTC, JinDouang requested changes

2023-07-17 07:36 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +import io.vertx.core.json.Json;
Import non utilisé

2023-07-17 07:36 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireApplicationStorage.java
> +    private final static Logger log = LoggerFactory.getLogger(FormulaireApplicationStorage.class);
```suggestion
    private static final Logger log = LoggerFactory.getLogger(FormulaireApplicationStorage.class);
```
spec' java sur les Modifiers (les classes, attributs etc..)

2023-07-18 07:50 UTC, JinDouang approved these changes

2023-07-18 09:00 UTC, BastienBenard approved these changes

2023-07-18 09:00 UTC, BastienBenard commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireApplicationStorage.java
> +    protected void getInfoProcess(final String fileId, final Handler<AsyncResult<FileInfos>> handler) {
@Override

2023-07-18 09:00 UTC, BastienBenard commented on formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFolderServiceTest.java
> +            async.complete();
Pas nécessaire, car tu l'a dans ton onSuccess

2023-07-18 09:00 UTC, BastienBenard commented on formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
> +            async.complete();
Pas nécessaire, car tu l'a dans ton onSuccess

2023-07-18 09:00 UTC, BastienBenard commented on formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
> +            async.complete();
Pas nécessaire, car tu l'a dans ton onSuccess

2023-07-18 10:08 UTC, merged