fix(question-type-matrix): #FOR-748 adapt axis label + add character limit
OPEN-ENT-NG/form pull request #363
Opened 2023-09-04 08:58 UTC by c4role

## Describe your changes
For matrix question graphics, we limit labels to 100 characters, and if they are longer than 50, we split them into two lines.
The directive has also been updated.

## Checklist tests
Create a matrix type question, try adding labels longer than 100 characters, you should not be able to do this; create one with less than 50 characters and more, and check in the results view if it is indeed split into two parts when it contains more than 50 characters.

## Issue ticket number and link
[FOR-748](https://jira.support-ent.fr/browse/FOR-748)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-09-04 09:09 UTC, qperie approved these changes

2023-09-04 09:09 UTC, qperie commented on common/src/main/resources/ts/utils/graph.ts
> +            const title = child.title;
typages ici et en-dessous

2023-09-04 09:41 UTC, Rseuret requested changes

2023-09-04 09:41 UTC, Rseuret commented on common/src/main/resources/ts/utils/graph.ts
> +            if (title.length > 50) {
tu mets 50 en limite alors que dans la description tu mets une limite de 100 donc les cas entre 50 < x <100  ne sont pas pris en compte

2023-09-05 07:12 UTC, Gregprod33 commented on common/src/main/resources/ts/utils/graph.ts
> +            if (title.length > 50) {
On peut définir une constante pour la limite

2023-09-05 09:35 UTC, Rseuret approved these changes

2023-09-05 09:38 UTC, Gregprod33 approved these changes

2023-09-05 09:41 UTC, merged