fix(restore): #FOR-753 update controller and service with the use of Form Models instead of jsonObjects
OPEN-ENT-NG/form pull request #364
Opened 2023-09-05 12:53 UTC by Gregprod33

## Describe your changes
Fixing some issue when trying to iterate through a jsonArray which contains a list of Models due to a modification of listByIds method in july. The consequence was a server exception error.
We change the way to iterate through this List of Models Form to set a property.
Also we modify the method updateMultiple in service to fit with the models and return a future <JsonArray> if succeed.
## Checklist tests

## Issue ticket number and link
[FOR-753](https://jira.support-ent.fr/browse/FOR-753)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-09-05 13:57 UTC, qperie requested changes

2023-09-05 13:57 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +    public Future<JsonArray> updateMultiple(List<Form> forms) {
Faire en sorte d'en faire une Future<List<Form>>

2023-09-05 13:57 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
>              s.raw(TRANSACTION_BEGIN_QUERY);
Utiliser les TransactionElement, le TransactionHelper etc.
Il y a un très bon exemple avec le QuestionService.update

2023-09-06 12:33 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +        String errorMessage = "[Formulaire@DefaultFormService::updateMultiple] Fail to update this forms";
```suggestion
        String errorMessage = "[Formulaire@DefaultFormService::updateMultiple] Fail to update these forms";
```

2023-09-06 12:33 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +            promise.fail("[Formulaire@DefaultFormService::updateMultiple] Empty Forms List, nothing to update");
```suggestion
            promise.fail("[Formulaire@DefaultFormService::updateMultiple] Empty forms list, nothing to update");
```

2023-09-06 12:33 UTC, qperie commented on common/src/main/java/fr/openent/form/helpers/DateHelper.java
> +        try {
```suggestion
        SimpleDateFormat dateFormatter = new SimpleDateFormat(format);
        Date result = new Date();
        try {
```

2023-09-06 12:33 UTC, qperie commented on common/src/main/java/fr/openent/form/helpers/DateHelper.java
> +    public static Date formatDateToModel(String property, String format) {
property c'est une date donc tu peux utiliser un nom de variable plus parlant comme les fonctions au-dessus avec inputDateStr par exemple

2023-09-06 12:33 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
> +                                        log.error("[Formulaire@FormController::restore] Failed to restore forms" + err.getMessage());
```suggestion
                                        log.error("[Formulaire@FormController::restore] Failed to restore forms : " + err.getMessage());
```

2023-09-06 12:33 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +                Form form = forms.get(i);
Tu peux faire un for each ce sera plus simple

2023-09-06 15:19 UTC, FlorentMr approved these changes

2023-09-07 07:07 UTC, merged