fix(saving): [#FOR-775] fix choice positions when going rogue
OPEN-ENT-NG/form pull request #383
Opened 2023-10-18 09:41 UTC by qperie

## Describe your changes
Check if choice positions are really following an order like [1,2,3,4] instead of [2,1,3,4] or [1,3,3,4] for instance (wron order, doubles, etc.)

## Checklist tests

## Issue ticket number and link
FOR-775 : https://jira.support-ent.fr/browse/FOR-775

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-10-24 08:29 UTC, JinDouang requested changes

2023-10-24 08:29 UTC, JinDouang commented on common/src/main/resources/ts/utils/utils.ts
> +        for (let i: number = 0; i < array1.length; i++) if (array1[i] !== array2[i]) return false;
Si je suis ton raisonnement : 

```
> areArrayEqual ([1,2,3], [1,3,4])
false
> areArrayEqual([1,2,3], [1,2,3])
true
> areArrayEqual([1,3,4,5], [1,2,3])
false
```

2023-10-24 08:29 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/controllers/form-editor.ts
> +                    for (let choice of formElement.choices.all) await questionChoiceService.update(choice);
Est-ce qu'il ne serait pas judicieux de stocker tes function async dans un tableau de promises pour faire un `await Promise.all([tableau_async])` ?

2023-10-24 08:54 UTC, qperie commented on common/src/main/resources/ts/utils/utils.ts
> +        for (let i: number = 0; i < array1.length; i++) if (array1[i] !== array2[i]) return false;
Exactement, et même
```
> areArrayEqual([1,2,3], [1,3,2])
false
```
L'idée est vraiment d'avoir les mêmes éléments dans le même ordre sinon c'est false

2023-10-24 09:13 UTC, qperie commented on formulaire/src/main/resources/public/ts/controllers/form-editor.ts
> +                    for (let choice of formElement.choices.all) await questionChoiceService.update(choice);
J'ai fais une nouvelle route API dans cette PR https://github.com/OPEN-ENT-NG/form/pull/384
Je met donc celle là en stand by et la rebaserai dessus une fois l'autre mergée afin d'utiliser ce nouveaux point API qui enregistre plusieurs choix en un unique appel 👍

2023-10-25 09:48 UTC, JinDouang approved these changes

2023-10-25 09:51 UTC, merged