feat(response): [#FOR-788] create new response API endpoints
OPEN-ENT-NG/form pull request #386
Opened 2023-11-17 11:20 UTC by qperie

## Describe your changes
Add multiple API endpoints for ResponseController.
Also improve some naming or variables' types.

Documentation : https://confluence.support-ent.fr/display/FOR/Response#operations-tag-default (WIP)

## Checklist tests

## Issue ticket number and link
FOR-788 : https://jira.support-ent.fr/browse/FOR-788

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-11-17 16:33 UTC, qperie commented
La documentation est en court d'écriture

2023-11-20 08:58 UTC, JinDouang requested changes

2023-11-20 08:58 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +    @Get("/distributions/:distributionId/responses/multiple")
Est-ce que cette API impacte l'appli mobile ?

2023-11-20 08:58 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +                if (!request.isEnded()) renderError(request);
Ca ne va pas du tout @Alex-Delaveau 
Pourquoi cette PR a été validé https://github.com/OPEN-ENT-NG/form/pull/385/files#diff-4a44466f7571a8b4a0af01c015040d19e42f515cc6ce7e8496053461f0915b7fR133 alors que ces retours n'ont pas été traité ?

@qperie Il faut traiter ce retour..

2023-11-20 08:58 UTC, JinDouang commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +                    if (!request.isEnded()) renderError(request);
Cette condition n'est pas nécessaire et peut même être grave si jamais la condition n'est pas rempli..

2023-11-20 14:20 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +    @Get("/distributions/:distributionId/responses/multiple")
Non c'était une erreur sur une nouvelle route d'un ticket précédent mais rien de livré encore

2023-11-20 14:22 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +                if (!request.isEnded()) renderError(request);
Retour expliqué 👍

2023-11-20 14:29 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +                    if (!request.isEnded()) renderError(request);
Juste au dessus on a déjà répondu à la request avec une 401 si jamais le user connecté n'avait pas les droits suffisant sur chaque ressource qu'on veut modifier : https://github.com/OPEN-ENT-NG/form/pull/386/files#diff-4a44466f7571a8b4a0af01c015040d19e42f515cc6ce7e8496053461f0915b7fR511

La future étant fail on arrive ici mais vu qu'on a déjà répondu à la request on a pas besoin d'y répondre une 2ème fois.
Ca permet d'obtenir au final une 401 plutôt qu'une 500 si on avait juste fait comme d'hab

2023-11-21 09:24 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +        Map<String, Object> composeMap = new HashMap<>();
Permet de stocker des valeurs de compose pour les réutiliser plus tard dans le flow (autre compose, onSuccess, etc.)

2023-11-21 09:24 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +            Map<String, Object> composeMap = new HashMap<>();
Permet de stocker des valeurs de compose pour les réutiliser plus tard dans le flow (autre compose, onSuccess, etc.)

2023-11-21 09:24 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +            Map<String, Object> composeMap = new HashMap<>();
Permet de stocker des valeurs de compose pour les réutiliser plus tard dans le flow (autre compose, onSuccess, etc.)

2023-11-21 10:45 UTC, JinDouang approved these changes

2023-11-21 13:32 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
> +        Map<String, Object> composeMap = new HashMap<>();
Permet de stocker des valeurs de compose pour les réutiliser plus tard dans le flow (autre compose, onSuccess, etc.)

2023-11-21 13:32 UTC, merged