fix(response): [#FOR-792] fix targeting system in responses views
OPEN-ENT-NG/form pull request #389
Opened 2023-11-20 11:14 UTC by qperie

## Describe your changes
Fix selection of the next element (target) according to the user response

## Checklist tests

## Issue ticket number and link
FOR-792 : https://jira.support-ent.fr/browse/FOR-792

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-11-20 14:55 UTC, Rseuret approved these changes

2023-11-20 16:35 UTC, JinDouang requested changes

2023-11-20 16:35 UTC, JinDouang commented on formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts
> +			let targetedElement = choices.length === 1 ? choices[0].getNextFormElement(vm.formElements, conditionalQuestion) : null;
typage FormElement ?

2023-11-20 16:35 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/controllers/form-editor.ts
> +                let targetedElement = choices.length === 1 ? choices[0].getNextFormElement(vm.formElements, conditionalQuestion) : null;
idem

2023-11-20 16:35 UTC, JinDouang commented on formulaire/src/main/resources/public/ts/controllers/respond-question.ts
> +            let targetedElement = choices.length === 1 ? choices[0].getNextFormElement(vm.formElements, conditionalQuestion) : null;
idem

2023-11-21 10:46 UTC, JinDouang approved these changes

2023-11-21 14:36 UTC, merged