Fix/wb 3350
OPEN-ENT-NG/form pull request #418
Opened 2024-09-27 14:05 UTC by Romu-C

## Describe your changes

One boolean was used to display the loading when we open the modal to add new element. The boolean was used for both saving the form and displaying the modal. We now have two different boolean for that so the opening of the modal isn't impacting by the saving form in the back.

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-10-01 15:17 UTC, juniorode requested changes

2024-10-01 15:17 UTC, juniorode commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +            e.printStackTrace();
Plutôt `log.error("gna gna gna", e);`

2024-10-01 15:17 UTC, juniorode commented on formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
> +            promise.fail(e.getMessage());
Tu peux faire `promise.fail(e)` directement.

2024-10-02 07:22 UTC, jcbe-ode reviewed
A part un détail mineur, ok pour moi

2024-10-02 07:22 UTC, jcbe-ode commented on common/src/main/java/fr/openent/form/core/models/Form.java
> +				    formattedDate = Optional.of(LocalDateTime.parse(inputDateStr, DateTimeFormatter.ofPattern(DateFormats.YYYY_MM_DD_T_HH_MM_SS_SSS)).atZone(ZoneId.systemDefault()));
Pas besoin de reconstruire le formatter à chaque appel car d'[après la doc](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#pattern)
> A formatter created from a pattern can be used as many times as necessary, it is immutable and is thread-safe.

=> Autant le construire 1 seule fois.

2024-10-07 12:11 UTC, merged