feat(matrix) : [FOR-436] - Creation and edition of matrix
OPEN-ENT-NG/form pull request #92
Opened 2022-08-29 13:50 UTC by qperie

## Describe your changes
We add a nex type of question : the matrix.
It includes : 
- display this new type in creation pop-up
- the matrix appears in form-editor page
- the matrix is editable
- the matrix can be deleted
- the matrix can be duplicated
- a form containing matrix questions can be duplicated

## Checklist tests

## Issue ticket number and link
FOR-436 : https://jira.support-ent.fr/browse/FOR-436

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-29 14:23 UTC, FlorentMr approved these changes

2022-08-29 14:23 UTC, FlorentMr commented on common/src/main/resources/ts/models/FormElement/Question.ts
> +                    for (let j = 0; j < 3; j++) {
Pas possible d'adapter le 3 en une variable? (sinon une constante?)

2022-08-29 14:23 UTC, FlorentMr commented on common/src/main/resources/ts/models/FormElement/Question.ts
> +                    for (let j = 0; j < 3; j++) {
Pas possible d'adapter le 3 en une variable? (sinon une constante?)

2022-08-29 14:23 UTC, FlorentMr commented on formulaire/src/main/resources/public/ts/controllers/form-editor.ts
> +                        for (let i = 0; i < 3; i++) {
Pas possible d'adapter le 3 en une variable? (sinon une constante?)

2022-09-05 06:15 UTC, JinDouang requested changes

2022-09-05 07:59 UTC, qperie commented on formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java
> +        for (Integer i = 0; i < request.params().size(); i++) {
Non parce que ligne suivante dans le for je fais un request.getParam(i.toString())

2022-09-06 06:35 UTC, JinDouang approved these changes

2022-09-06 08:03 UTC, FlorentMr approved these changes

2022-09-06 08:05 UTC, merged